services:
  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pg-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "betoakang@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - 16543:80
    depends_on:
      - postgres_db
